ui/src-tauri/src/main.rs
Currently, the main window of Signer won't close (or do anything) if you click the red dot on mac (or X on windows). This PR changes behavior so that Signer quits entirely when you click the red dot on mac (or X on windows).
=> close app on quit window

Cargo.toml, release.sh, src/service.rs, ui/package.json, ui/public/about.html, ui/src-tauri/Cargo.lock, ui/src-tauri/Cargo.toml, ui/src-tauri/tauri.conf.json
-Replaces `heartbeat` endpoint with `version` endpoint
-Uses new version of [manta-api](https://github.com/Manta-Network/manta-api/pull/46), which has small type changes needed for incremental recovery
=> Incremental recovery changes

FILE_TEMPLATE, examples/test_server.rs, src/batching.rs, src/config.rs, src/lib.rs, src/secret.rs, src/service.rs, ui/public/about.html, ui/src-tauri/src/main.rs, ui/src-tauri/tauri.conf.json
Update copyright year on about page / config files / file headers
- [ x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
n/a (no logical changes)
n/a (nothing to document)
- [x ] Re-reviewed `Files changed` in the Github PR explorer.
* Cargo.toml
n/a (no logical changes)
=> update copyright text

.github/workflows/release.yml
closes: #XXXX
---
* Cargo.toml
=> Get Proving Keys from Git-LFS

.github/workflows/release.yml, ui/src-tauri/Cargo.lock, ui/src-tauri/src/main.rs
new build step for ubuntu 18.04, fixes issue with about window popping up on ubuntu machines.
---
* Cargo.toml
=> Add ubuntu 18

.github/workflows/release.yml, release.sh, src/config.rs, ui/.gitignore, ui/src-tauri/tauri.conf.json
Updates to new SDK, which has a legacy file path for old proving keys.
---
* Cargo.toml
=> feat: move to new sdk, which requires legacy file locations

.github/workflows/tag.yaml
Fixes the previous CI pipeline for releases.
---
* Cargo.toml
=> fix: use the correct tag_name argument

.github/workflows/release.yml
Tauri no longer has issues between macOS 10.15 and macOS latest, so we can just use a unified build.
---
* Cargo.toml
=> fix: remove macos 10.15 from CI [#none]

ui/src/App.css
When selecting the text in the recovery phrase section, because of the current light-blue background color, users may select only part of the mnemonic without noticing. Changing the css of the selection makes the selection obvious.
changes copied from #90 , because signer CI is failing to build signer on that branch, possibly because PR is from external contributor
---
* Cargo.toml
=> highlight recovery phrase selection;

.github/workflows/create_release.yaml, .github/workflows/release.yml, Cargo.toml, ui/package.json, ui/public/about.html, ui/src-tauri/Cargo.lock, ui/src-tauri/Cargo.toml, ui/src-tauri/tauri.conf.json, ui/src/pages/CreateAccount.js, ui/src/pages/SignIn.js, ui/yarn.lock, www/src/App.tsx
Add token for workflow trigger, add some error hints.
---
* Cargo.toml
* www/src/App.tsx
=> Upgrade tauri, add some messages

Cargo.toml, src/log.rs, src/parameters.rs, src/service.rs
Parameters have been moved from SDK to manta-parameters, including `ProvingContext`, `VerifyingContext`, `Parameters`, and `UtxoAccumulatorModel`. We need to update the parameter path correspondingly in `manta-signer`.
closes: #118 
---
* Cargo.toml
* www/src/App.tsx
=> feat: update parameter path from SDK to manta-parameters

.github/workflows/ci.yml, Cargo.toml, src/service.rs
Downgrade manta-rs
---
the type interfaces introduced in manta-rs v0.5.3 and higher are "ahed" of the type interfaces in Manta runtime
=> downgrade manta-rs

ui/src-tauri/src/main.rs
Fixing connection timeout after while_timeout was refactored wrong making it timeout even after succesful connection
Signed-off-by: Apokalip <simeon@manta.network>
fixes: #169 
---
=> Connection timeout after successful timeout fix

CHANGELOG.md, src/config.rs, src/service.rs
Signed-off-by: Brandon H. Gomes <bhgomes@pm.me>
Adds https://app.manta.network to the CORS allowed origins setting and general support for multiple origins in the future.
---
=> feat: add multiple origin URLs for CORS

README.md
Signed-off-by: Simeon Zahariev <43317481+Apokalip@users.noreply.github.com>
closes: #189 
---
=> Update readme for building Manta Signer

CHANGELOG.md, Cargo.lock, src/config.rs, src/service.rs
Added checking for existence of backup file upon signer startup. This fixes the bug where the user would not be able to login to signer with the correct password if they exited the signer while new state file was still being written to, leading to a corrupt state.
---
=> Add checking for backup file

CHANGELOG.md, src/config.rs
Fix to check for storage file before we delete it to replace it with backup file. This is an edge case where only the backup file exists without the storage file upon startup and would cause a crash if we tried to delete a non-existing storage file.
---
=> fix: check for old storage file before deleting it

CHANGELOG.md, src/service.rs
Signed-off-by: Charles Ferrell <charlie@manta.network>
Small bug fix with reloading a missing file. It mixes up different networks
---
=> Fix Missing File Reload

CHANGELOG.md, src/parameters.rs
Signed-off-by: Apokalip <simeon@manta.network>
---
=> linux proving keys

CHANGELOG.md, src/service.rs, ui/src-tauri/src/main.rs, ui/src/App.js, ui/src/pages/Authorize.js, ui/src/pages/ViewPhrase/ViewPhrasePage.js, ui/src/pages/ViewPhrase/ViewSecretPhrase.js
Signed-off-by: Apokalip <simeon@manta.network>
closes: #281
closes: #280
closes: #242
closes: #232 
---
=> Fix authorization

CHANGELOG.md, Cargo.toml, ui/package.json, ui/public/about.html, ui/src-tauri/Cargo.toml, ui/src-tauri/tauri.conf.json, www/src/App.tsx
**Each reviewer needs to check that these conditions are met before approving the PR.**
=> Release 1.1.1

.github/workflows/release.yml, CHANGELOG.md, ui/src-tauri/src/main.rs
Creating a server after restart, creates a bad app state so even after properly syncing, transactions would not pass. After restart there is no need for a new server, only case may be when we do a password reset where we do want to keep the password storage
closes: #330 
=> Fix reimport / password reset

CHANGELOG.md, ui/src/pages/SignIn/SignInSuccess.js
---
Removes "soon" text next to Calamari now that is has been enabled
=> Remove "soon" next to calamari for Calamari release
